### ISSUE TITLE
Appreciation Post

### ISSUE THREAD

**Issue by vijayksingh** [bobocode-projects/java-fundamentals-course#101]
It's one of the best hands-on resources to get your hands dirty with Java. 
I really like the exercise quality and difficulty level, they do tend to teach something new about java. 

I also went through your org website. Kinda felt disappointed to see all the teaching material is in Russian only. Would appreciate if you guys can create any course for English viewers.

**Comment by tboychuk** [comment]
Thank you @vijayksingh for the support!
